### ISSUE TITLE
Getting camera intrinsics and extrinsics

### ISSUE THREAD

**Issue by rakeshshrestha31** [isl-org/redwood-3dscan#1]
Thank you for sharing this dataset. I couldn't find the camera intrinsics and extrinsics for the images in this dataset. Is there a way to get those?

**Comment by lilanxiao** [comment]
The intrinsic is given at the homepage (http://redwood-data.org/3dscan/):
> The focal length is 525 for both axes and the principal point is (319.5, 239.5). The depth images are registered to the color images.

The extrinsic is not given though. Users probably have to reconstruct the scenes by themselves.

**Comment by rakeshshrestha31** [comment]
@lilanxiao Thank you. I'll close this issue then
